### ISSUE TITLE
How to download the latest from script?

### ISSUE THREAD

**Issue by gandhidarshak** [vim/vim-appimage#12]
Is there a weblink which will always point to the latest AppImage so I can download the latest using some script whenever I want to update?

**Comment by chrisbra** [comment]
Try this one:
https://github.com/vim/vim-appimage/releases/latest

Note, if creating the appimage failed, it probably won't resolve correctly.

**Comment by chrisbra** [comment]
you might be able to script something using wget or curl, not sure.
