### ISSUE TITLE
Doesn't find correct terminfo entry

### ISSUE THREAD

**Issue by hupfdule** [vim/vim-appimage#14]
When starting vim from this appimage (version 8.1.2135) I get the following error:
```
E558: Terminal entry not found in terminfo
'tmux-256color' not known. Available builtin terminals are:
    builtin_gui
    builtin_amiga
    builtin_beos-ansi
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
```

This doesn't happen with the vim distributed in Debian and it also doesn't happen with a a self-compiled vim (version 8.1.2136).

**Comment by chrisbra** [comment]
most likely, the terminfo database is not available in the sandboxed appimage. So use a builtin terminal description.

**Comment by hupfdule** [comment]
Ok. Thank you. Then I will do that. 

And it is not likely to break when using vim under urxvt, but using `TERM=xterm`?

**Comment by chrisbra** [comment]
it might. You have to try out.
