### ISSUE TITLE
Hello, and thanks for your appimage.

### ISSUE THREAD

**Issue by boput** [vim/vim-appimage#15]

**Comment by boput** [comment]
Hi again. I downloaded latest appimage to run it on Ubuntu 19.10. If I double click on the image, it takes about 30 seconds to get Gvim running. if I run it from terminal I get following messages and about 30 seconds later I get Gvim running.:
bozidar@bozidar-NUC7CJYH:~/apps$ ~/apps/vim/GVim-v8.1.2383.glibc2.15-x86_64.AppImage test.txt
Gtk-Message: 18:23:00.100: Failed to load module "atk-bridge"
Gtk-Message: 18:23:00.136: Failed to load module "canberra-gtk-module"

Please note, there are not issues with running vim.appimage in the terminal window, onlu with Gvim.

**Comment by chrisbra** [comment]
I think that is just a warning that can be ignored.

**Comment by boput** [comment]
Agree. It must be some issue with Ubuntu to need about 30 sec to start Gvim. Again, vim.appimage runs as it should.
