### ISSUE TITLE
Gvim (vim) cannot find file

### ISSUE THREAD

**Issue by boput** [vim/vim-appimage#16]
Hi, this is the output of latest appimage GVim-v8.2.0011.glibc2.15-x86_64.AppImage.

Gvim/vim is trying to open syntax file in:
/tmp/.mount_gvimpH5q6T/usr/share/vim/**vim81**/syntax/syntax.vim

but it cannot find it, as the unsquashed image in /tmp is:
tmp/.mount_gvimpH5q6T/usr/share/vim/**vim82**/syntax/syntax.vim

Here is the output of vim messages:

Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /home/bozidar/.local/share/nvim/site/vim-sensible/plugin/sensible.vim:
line   15:
E484: Can't open file /tmp/.mount_gvimpH5q6T/usr/share/vim/**vim81**/syntax/syntax.vim
wombat256mod
No Syntax items defined for this buffer
E484: Can't open file /tmp/.mount_gvimpH5q6T/usr/share/vim/**vim81**/syntax/syntax.vim

**Comment by chrisbra** [comment]
Thanks for noticing! should be fixes with 46f5b064f2173dc
