### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by zhmars** [vim/vim-appimage#17]
Hi, thanks for this appimage.

Correct me if I'm wrong. Currently, this package is buildt with `Python 3.4`, which means we will unable to get python3 support if our python version is more than 3.4.

According to the [release schedule](https://www.python.org/dev/peps/pep-0429/#release-schedule)
> Python 3.4 has now reached its end-of-life and has been retired. No more releases will be made.

Would it be possible to upgrade to latest Python 3.8?

**Comment by chrisbra** [comment]
IIRC, this is based on Ubuntu 14.04 LTS. That does not seem to come with python3.8 so I am not sure this is possible without having to install additional packages. And then I wonder, whether the appimage will still work
