### ISSUE TITLE
gvim: error while loading shared libraries: libgdk_pixbuf-2.0.so.0

### ISSUE THREAD

**Issue by ghost** [vim/vim-appimage#19]
Keep getting this error: gvim: `error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory`

Doing `./GVim-v8.2.0363.glibc2.15-x86_64.AppImage --appimage-extract`, I don't see this `.so` file bundled in.

**Comment by chrisbra** [comment]
don't know.
