### ISSUE TITLE
GTK Gui

### ISSUE THREAD

**Issue by siddharth99** [vim/vim-appimage#2]
Thanks for providing these vim appimages; they are really helpful. However, I was wondering if it would be easy to provide appimages based to gtk gui instead of x11-athena; I have been using an old appimage from the older repo chrisbra/vim-appimage which is compiled with gtk gui.

**Comment by fusion809** [comment]
I second this, the Athena GUI looks terrible to me, at least.

**Comment by fusion809** [comment]
I've managed to create a GTK+2 supporting GVim AppImage from forking this repo ([fusion809/vim-appimage](https://github.com/fusion809/vim-appimage)) and making some minor changes. Feel free to give them a go, here's the releases page &mdash; https://github.com/fusion809/vim-appimage/releases.

**Comment by chrisbra** [comment]
So I guess, the only change would be add `--enable-gui=gtk2` and add the dependency for libgtk2.0-dev, right?

**Comment by fusion809** [comment]
Yep seems like it works.

**Comment by chrisbra** [comment]
okay, I made #3 I'll be awaiting some comments before merging.
