### ISSUE TITLE
E837: This Vim cannot execute :py3 after using :python

### ISSUE THREAD

**Issue by ryanbrate** [vim/vim-appimage#20]
Hi,

I seem to have an issue with compiled python support of the AppImage.
I get the following error (triggered by the ultisnips plugin)

`E837: This Vim cannot execute :py3 after using :python`

I'm running Debian 10.
Note: I'm assuming it's a problem with the appimage, as the error does not appear with the distro-bundled vim, or an nvim appimage I tried.

Thanks and regards,

Ryan

**Comment by chrisbra** [comment]
The error says it all, you cannot use Python 3 after having used python2. That is not a bug.

**Comment by ryanbrate** [comment]
Thanks for the swift reply.

Do you know why it's only a problem on the AppImage build? And also, what I can do about it?

Thanks

**Comment by brammool** [comment]
> Do you know why it's only a problem on the AppImage build? And also,
> what I can do about it?

It is explained at ":help E836".

-- 
ARTHUR: If you do not open these doors, we will take this castle by force ...
   [A bucket of slops land on ARTHUR.  He tries to retain his dignity.]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
