### ISSUE TITLE
Error libgdk_pixbuf-2.0.so.0

### ISSUE THREAD

**Issue by yelled1** [vim/vim-appimage#21]
Wonderful effort & had fun with it, Until, I attempted to run it on GUI & internet less server & I get libgdk_pixbuf-2.0.so.0.

So, I followed the instruction &:
Arch$ ln -s GVim-v8.1.1209.glibc2.15-x86_64.AppImage vim.appimage
Arch$ ls -l vim.appimage
lrwxrwxrwx 1 ny11559 domain users 40 May  1 18:22 vim.appimage -> GVim-v8.1.1209.glibc2.15-x86_64.AppImage
Arch$ vim.appimage
vim.appimage: command not found
/Arch$ chmod +x vim.appimage
chmod: cannot operate on dangling symlink 'vim.appimage'

Also, I attempted to copy to name vim.appimage:
but got
vim: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory

What am I doing wrong?
Thank you much,

**Comment by yelled1** [comment]
Hmm, trying to compile using scripts/build_vim.sh
cloned vim into vim-appimage/vim
Eliminated --enable-gui=gtk2 + pearlinterp, rubyinterp, luaitnerp, & tclinterp.
Tried to compile & all of a sudden the terminal closed.
Is there anything special about directory structure or tools that I need?
I have Ubuntu 18.04 (elementary) & 20.04 w/ WSL.

**Comment by chrisbra** [comment]
the directory structure shouldn't matter.
