### ISSUE TITLE
Link to latest stable

### ISSUE THREAD

**Issue by hiqsol** [vim/vim-appimage#22]
Is there a way to have a link to download the latest stable release?
I want to have a script installing the latest version.
Thanks!

**Comment by chrisbra** [comment]
That one should always work: https://github.com/vim/vim-appimage/releases/latest

**Comment by hiqsol** [comment]
Thank you! But that's a link to the download page, not the downloadable file.

I did some googling. Here is how to find the link:

```sh
curl --silent "https://api.github.com/repos/vim/vim-appimage/releases/latest" | jq -r 'first(.assets[].browser_download_url)'
```

And here is a shell function to install and run vim8 instantly:

```sh
vim8() {
    file="$HOME/bin/vim8"

    if [ ! -x $file ]; then
        url=`curl --silent "https://api.github.com/repos/vim/vim-appimage/releases/latest" | jq -r 'first(.assets[].browser_download_url)'`
        curl -L $url -o $file
        chmod a+x $file
    fi

    $file $@
}
```

**Comment by chrisbra** [comment]
ah yes sorry, did not know a fully automatable way. Good that you found a solution. 👍

**Comment by brammool** [comment]
> That one should always work:
> https://github.com/vim/vim-appimage/releases/latest

Let me add that link to https://www.vim.org/download.php
Should it say more about what it is?

-- 
ARTHUR:        I command you as King of the Britons to stand aside!
BLACK KNIGHT:  I move for no man.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
It's a way to distribute apps on linux independently of the distribution and can be used by normal users, without needing root permissions. This allows to run a pretty recent graphical gui (gtk2) with most features even if your distro does not provide newer packages. However I believe the language interfaces still need those libraries available.
