### ISSUE TITLE
Provide update information

### ISSUE THREAD

**Issue by azubieta** [vim/vim-appimage#23]
The AppImage format support delta updates using zsync files. For this to work an update information string must be passed when the AppImage is being built, like this:

`appimagetool AppDir -u "gh-releases-zsync|vim|vim-appimage|latest|GVim-*x86_64.AppImage.zsync"`

A `zsync` file will be generated next to the AppImage file, both file must be published as release artifacts.

Please check: 
- https://docs.appimage.org/packaging-guide/optional/updates.html
- https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases

**Comment by chrisbra** [comment]
Please be more specific. What do you think is wrong currently?

**Comment by azubieta** [comment]
Nothing is wrong, just missing. I updated the issue description

**Comment by chrisbra** [comment]
okay, let's see if this works :/

**Comment by chrisbra** [comment]
how do you then use the zsync file?

**Comment by azubieta** [comment]
Applications such as AppImageUpdate or appimage-manager make use of it to update the AppImages. 

- https://github.com/AppImage/AppImageUpdate
- https://github.com/AppImageCrafters/appimage-manager

**Comment by chrisbra** [comment]
I see, thanks!
