### ISSUE TITLE
Create a console only appimage too

### ISSUE THREAD

**Issue by crash5** [vim/vim-appimage#27]
Hi!

I try to use the appimage on a Debian 10.8 server without X window, but it is always complaining about missing files `libXt.so.6` and `libXcomposite.so.1`. (the first file is in the `libxt6` package, but for the second file it want to install a lot of gtk and X depentent packages).

Can you provide an appimage without the X/gtk depencencies please?

**Comment by skywind3000** [comment]
any conclusion about this ??

**Comment by chrisbra** [comment]
no, let me re-open this then

**Comment by inspired-dialect** [comment]
Hi @crash5,

Have you tried to use `./GVim-*.AppImage -v` yet?

**Comment by chrisbra** [comment]
that most likely won't work, if you do not have the libraries installed.

**Comment by jazei-AR** [comment]
I downladed version 9 but I don´t know  how install it...
what should I do?.

**Comment by chrisbra** [comment]
Run it

**Comment by mthbrown** [comment]
Having a console only version would be nice as you can easily use it on remote boxes where you aren't `root`

**Comment by ychin** [comment]
I think we just need to make a separate release with configure flags `--enable-gui=no --with-x=no` (need to add these to https://github.com/vim/vim-appimage/blob/master/scripts/build_vim.sh), and from local testing with `ldd`, this does strip the `libXt.so` dependency from the binary. Removing X support also removes clipboard support.

I think the question is mostly how many configurations this release should support? It does sound like a headless-capable (meaning no X dependency) version would be useful, especially given Applmage's main advantage of not needing permission and can be dropped and run.

**Comment by skywind3000** [comment]
bravo

**Comment by skywind3000** [comment]
seems like the new release event is not triggered

**Comment by chrisbra** [comment]
yeah, some minor issues with the ci. I think I fixed it now, but now a single test fails :(
