### ISSUE TITLE
Release stopped

### ISSUE THREAD

**Issue by k-takata** [vim/vim-appimage#29]
It seems that the releases are stopped because no credits left for Travis CI.
It might be better to switch to GitHub Actions.

**Comment by crash5** [comment]
> It seems that the releases are stopped because no credits left for Travis CI.

The maintainers can request more credits for OSS projects (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment...

**Comment by chrisbra** [comment]
yes, known issue. I haven't had time to port to github actions (and I heard various reports, that requesting more credits just did not work)

**Comment by chrisbra** [comment]
this has been fixed a long time ago.
