### ISSUE TITLE
What python version does this appimage link to ?

### ISSUE THREAD

**Issue by skywind3000** [vim/vim-appimage#35]
I downloaded this appimage in Ubuntu 22.04 and found that only `python2` was available, while `has('python3')` returned `0`.

Is this a version mismatch problem ?

The python3 package version in ubuntu 22.04 is `3.8.10`

**Comment by chrisbra** [comment]
It is using python3.6. Have you tried first testing for python3 before python 2?

**Comment by skywind3000** [comment]
I have called `has('python3')` at the very beginning, I knows they will conflicts.

And the system vim (the ubuntu apt package) can use `+python3` with the same config.

Maybe it is just expecting `libpython3.6.so` and can't link to my `libpython3.8.so` ??

**Comment by chrisbra** [comment]
no sure, perhaps setting 'pythonthreedll' to your `libpython3.8.so` works?

**Comment by skywind3000** [comment]
I put this in my vimrc before everything:

```viml
et pythonthreedll=/lib/x86_64-linux-gnu/libpython3.8.so
call has('python3')
```

and

```viml
:echo has('python3')
```

returns 1 now, but when I input a simple python command:

```viml
:py3 print(1234)
```

the command was executed but with a warning:

> <string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by skywind3000** [comment]
I found the root cause: 

- the macro `PY_VERSION_HEX` at the compiling time is defined as `0x03060000` or something.

and line 6937 to 6968 from `if_py_both.h` are affected by this:

![图片](https://user-images.githubusercontent.com/3035071/188113562-45b7171e-1e32-497b-abd7-b8f92198f595.png)



see the url:

https://github.com/vim/vim/blob/a906e8e1abf0a4c9a058ec5ee8a4c321a008cd41/src/if_py_both.h#L6937-L6968

the [importlib](https://docs.python.org/3/library/importlib.html) module was introduced early in python3.1

and [imp](https://docs.python.org/3/library/imp.html) module exists in python2 and deprecated in python3.4

this seems to be too strict:

```c
#if PY_VERSION_HEX >= 0x030700f0
    if (!(imp = PyImport_ImportModule("importlib.machinery")))
	return -1;
    ...
#else
    if (!(imp = PyImport_ImportModule("imp")))
	return -1;
    ....   
#endif
```

**Comment by chrisbra** [comment]
hm, you may want to create a PR at vim/vim then.

Also, I wonder if we should enable python3.8 for the appimage. Not sure if the following patch would be sufficient:

```diff
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
index 6e9baac..f51b2d4 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -79,7 +79,7 @@ jobs:
             libcanberra-dev \
             libperl-dev \
             python-dev \
-            python3-dev \
+            python3.8-dev \
             liblua5.3-dev \
             lua5.3 \
             ruby-dev \
```

**Comment by skywind3000** [comment]
> Also, I wonder if we should enable python3.8 for the appimage. Not sure if the following patch would be sufficient:

It is sufficient for this. changing appimage to python3.8 would be a better choice, since:

1) ubuntu 20.04 (released in 2020) ships with python3.8
2) ubuntu 22.04 (released in 2022) ships with python3.10
3) debian 12 (scheduled in the middle of 2023) will ship with python3.11
4) ubuntu 24.04 (2024) will ship with python3.12

changing appimage to python3.8 will have better compatibility with the main-stream linux distributions in the next few years.

**Comment by ychin** [comment]
Hmm this is interesting. FWIW it's not 100% safe to load `pythonthreedll` with a different Python version from the one Vim was compiled with (in this case 3.8) since they aren't guaranteed to be binary compatible. My PR (https://github.com/vim/vim/pull/12032) is supposed to fix this though with using stable ABI (which you would need to turn on using a configure flag, which I think AppImage builds may want to do).

Even with stable ABI though the issue here would still have happened, so I guess it's not a panacea (stable ABI only guarantees binary interface compatibility, but there are other wayrs to have incompatibility).
