### ISSUE TITLE
Unable to open files on command line

### ISSUE THREAD

**Issue by embear** [vim/vim-appimage#4]
Thanks for providing the appimage of Vim. This is very helpful to work with a recent Vim version on my very old Ubuntu at work.
I'm having some trouble starting Vim on command line with a file as argument. For example `$PWD` is `$HOME` and I issue `~/bin/GVim-v8.1.0139-gita8a60d0c6-glibc2.15.glibc2.15-x86_64.AppImage .bashrc` Vim will open a file in `/tmp/.mount_qMpnvg/usr/.bashrc` instead of `$HOME/.bashrc`. I tried to add `-c "cd $PWD"` which has no effect as it is executed after reading the file. Adding `--cmd "cd $PWD"` does not work because in this case the runtimepath variable contains wrong directories (not absolute paths) and the distributed configuration is not found.

Any ideas how to get this running?

**Comment by chrisbra** [comment]
sorry, this issue fell through. I hope to have it soon fixed, once #5 is merged.
