### ISSUE TITLE
Consider to enable python-stable-api for appimage build ?

### ISSUE THREAD

**Issue by skywind3000** [vim/vim-appimage#62]
The python-stable-api works quite well in the Window nightly builds.

Having been using it for one month, I believe it is stable enough.

Can we enable this for the appimage build too, please ?

**Comment by skywind3000** [comment]
thanks

**Comment by mralusw** [comment]
commit 39f585d did not fix the issue, but instead **disabled** python3, enabled python2 and introduced a (broken, but ignored) `--with-python3-stable-abi` (this flag actually needs a value).
