### ISSUE TITLE
Vim AppImage configuration not persisting across sessions

### ISSUE THREAD

**Issue by KevinGIRAULT** [vim/vim-appimage#64]
I have encountered an issue with the Vim AppImage where the configuration settings are not persisting across sessions. Each time I close Vim and reopen it, I have to specify the vimrc file again, and plugins need to be reinstalled using pluginstall.

Expected Behavior:
I expect Vim AppImage to retain the configuration settings and installed plugins between sessions, allowing for a seamless and persistent user experience.

Steps to Reproduce:

    Download Vim AppImage.
    Open Vim using the AppImage.
    Specify a vimrc file and install plugins.
    Close Vim.
    Reopen Vim using the AppImage.

Actual Result:
The configuration settings and installed plugins are not retained, and Vim starts with default settings.

You might think it's just a :source /path/to/folder/.vimrc but it's really annoying, for example for the codeium plugin (an alternative to copilot) where you have to enter your token each time, via the browser.

Environment:

    Operating System: MXlinux 21.3 (Wildflower)
    Vim Version: Vim: v9.1.0029 (https://github.com/vim/vim-appimage/releases/tag/v9.1.0029)

Thank you

**Comment by chrisbra** [comment]
> Specify a vimrc file and install plugins.

What does that mean?

**Comment by KevinGIRAULT** [comment]
> > Specify a vimrc file and install plugins.
> 
> What does that mean?

`:source path/to/.vimrc` and `PlugInstall`

Thank you for you reply.

**Comment by chrisbra** [comment]
so you need to re-source the `vimrc` after restart. Did you do that?

**Comment by KevinGIRAULT** [comment]
That's precisely the problem.

I have to do it again and again. That's precisely the problem.

I have to do it again and again. Because all the configuration is lost, a blank vim with no configuration

**Comment by chrisbra** [comment]
so is the question about how to use a different `vimrc` file then?

**Comment by chrisbra** [comment]
Please read the documentation on `:h .vimrc` about what places for initialization files are searched for.

**Comment by chrisbra** [comment]
I tested it. The appimage loads your usual `vimrc` file. It seems you do not have a specific problem with this repository but rather a usage question. Please use https://vi.stackexchange.com/ to ask user questions.
