### ISSUE TITLE
Runtime path doesn't include help tags.

### ISSUE THREAD

**Issue by TheDreadedAndy** [vim/vim-appimage#74]
As of the AppImage for version v9.1.0610, the tags file in vim91/doc is missing, which means most help commands will fail.

The command works in the AppImages for versions v9.1.0608 and below. The issue appears to be caused by [v9.1.0609](https://github.com/vim/vim/commit/4c3616d7a2c8c3b828e4d4ebbcd43e4a22154262), though I am not totally how.

**Comment by chrisbra** [comment]
thanks for noticing. I think I have fixed it now again.
